### ISSUE TITLE
CD Image with external WAV audio crashes

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-pce-fast-libretro#12]
It happens since July commits. 
Don't have nightlies archive to tell when exactly.

Tested with several cue+bin+ogg games that are working with older version.
Win7 x64, nothing relevant in the log.

**Comment by twinaphex** [comment]
Well, the only PC Engine CD games I usually test is Dracula X, and that still runs fine as of today (LInux x86_64).

**Comment by Tatsuya79** [comment]
Nothing in the log but I can see an "unsupported audio file format" in the retroarch dos window if I launch without logging.
Tried with ogg and with wav images, both crash at launch.

**Comment by twinaphex** [comment]
Guess we'll have to dissect it.

As a sidenote: I really, really dislike how the Mednafen author turned this into a kitchensink of audio formats which Mednafen PSX supports, which will lead to more and more sites putting up all sorts of dumps with varying audio format containers and the like. That's a bullet that should have been dodged so that we could have one proper set of CD dumps instead of all these confusing audio formats which require us to pull in all sorts of bloated dependencies on the core side.

**Comment by Tatsuya79** [comment]
Well, at least one open source format such as ogg is nice to have.
Uncompressed audio is such a waste of space, particularly for mobile platform.

Websites with bad dumps are still there even for roms.

**Comment by Tatsuya79** [comment]
I did a revert HEAD~5 back to the "Remove MD5" commit and now ogg are working.

For wav I'm at a loss with strange results; I should test more with a real iso (without dis-embedded audio files).

**Comment by twinaphex** [comment]
Can you actually track down at which point ogg no longer works, or did it occur exactly after HEAD~5?

**Comment by Tatsuya79** [comment]
"Downsize tremor" is the commit breaking it.

**Comment by Tatsuya79** [comment]
About the WAV case, in win7 x64, they always crash and tell:
"Retroarch [libretro ERROR] unsupported audio track file format: 01.wav"
Even when going back to a January version of pce_fast core.

Those cue+iso+WAV are working in Mednafen stand-alone.
I'm wondering if that ever worked in Retroarch or if I always used OGG version?
Or did it broke way earlier?

**Comment by twinaphex** [comment]
Its not so much a regression as it is that we took wav plus the dependency that came with it out.

I guess we could add it back again for those dumped cds that need it, but still, this support every cd format plus the kitchensink is very annoying since it pretty much ensures bloat in the core and divergent cd dumps.

**Comment by Tatsuya79** [comment]
Tested working since Revert "Downsize tremor" commit.
Closing this.

**Comment by twinaphex** [comment]
What about the ISO+WAV issues?

**Comment by Tatsuya79** [comment]
Yes I can keep it opened for that, sure.

**Comment by Tatsuya79** [comment]
I could test a cue+iso without external audio files and it worked.

**Comment by rdbaaa** [comment]
I'm having this problem on Win10 -- instant crash as soon as the cue is chosen (the audio is wav). RA 1.3.4 and latest core from the updater. 
My hardware is an Intel NUC with Intel Graphics 520 and driver updates haven't fixed it either.

However, it works perfectly fine on a 2010 laptop that's on Intel but also Win10 -- same builds and configs. Perhaps it's just a case of too-new hardware.
[log.txt](https://github.com/libretro/beetle-pce-fast-libretro/files/321590/log.txt)

**Comment by danhermle** [comment]
Hey guys.  I'm noticing the same issue using 1.3.6.  When I load a CUE/WAV format game RetroArch crashes immediately.  The last entry in the log says RetroArch [libretro INFO] :: Loading...  Then CTD.

CCD/IMG formatted games are fine.  These CUE/WAV images also work in vanilla mednafen.

**Comment by Tatsuya79** [comment]
Fixed with https://github.com/libretro/beetle-pce-fast-libretro/commit/fc0cf49fe6f301b4958c9960c00a3bf7fcc2e9b6
