### ISSUE TITLE
Update core to 1.23.0

### ISSUE THREAD

**Issue by ToniBC** [libretro/beetle-pce-fast-libretro#125]
Mednafen was recently updated with several corrections of this emulator and it would be nice to include them to improve those small errors. I don't know if some have already been applied, but since the core only reflects that it is in 0.9.38.7 Fast, they supposedly were not added.

After 0.9.38.7 this is what they changed:

- PCE, PSX, PCE_FAST: Avoid UB by biasing uintptr_t values instead of pointers directly in the CPU core.
- PCE, PCE_FAST: Added a missing sound emulation variable to save states.
- PCE_FAST: Fixed fubared mouse emulation.

As always, thank you very much for the effort and this is only to remember that it is pending to update the core.

**Comment by mrjschulte** [comment]
Had a quick look at doing this and the amount of work needed is not insignificant.

**Comment by hizzlekizzle** [comment]
That's a shame, but thanks for looking into it :)

**Comment by ToniBC** [comment]
Not everything has to be done at one time, little by little it can be improved to update it, it is what happens when the projects "leave" for a long time.

I left this to remember that a revision is needed so that this core is at the same level as the base and that the emulation is better.

But anyway, thanks for looking a little.

**Comment by negativeExponent** [comment]
the core is base on pce_fast, which with its libretro modifications can be called pce_fast_fast (yeah). So removing issue only for PCE and SuperGrafx, these are the relevant changes:

PCE, PSX, PCE_FAST: Avoid UB by biasing uintptr_t values instead of pointers directly in the CPU core.
PCE, PCE_FAST: Added a missing sound emulation variable to save states.
PCE_FAST: Fixed fubared mouse emulation.

doesn't look like game-breaking atm though. will probably look into it sometime unless someone does it first (does anyone care here about states compatibility, coz that will break with the changes)

**Comment by ToniBC** [comment]
This I published 1 year ago, when the other core was not there or the two branches were together, the PCE and PCE Fast. That is why the changes are included in the two cores.

**Comment by negativeExponent** [comment]
looking at past PR's, it seems that i have already addressed these before
* Avoid UB by biasing uintptr_t values instead of pointers directly in the CPU core - https://github.com/libretro/beetle-pce-fast-libretro/commit/83a234a1c74ea4a626e0a6b92197784e4887e0ae
* Fixed fubared mouse emulation. - https://github.com/libretro/beetle-pce-fast-libretro/commit/5a1cfa475f4a8ead993150ba0f506e22f156c273

I skipped save states coz it will break compatibility. So, its just a matter of bumping the version number which i havent dont coz there is really nothing much related changes to the core since 9.39.2

**Comment by negativeExponent** [comment]
needless to say, since the missing save states are not harming anything atm. its probably safe for this to close until some major updates are pushed upstream.
