### ISSUE TITLE
Crackling audio in some games, not present in standalone Mednafen

### ISSUE THREAD

**Issue by vanfanel** [libretro/beetle-pce-fast-libretro#21]
There's a an audio problem with some games in the beetle-pce core vs standalone mednafen. 
Audio in games like Space Harrier or Out Run has very noticeable crackling: it's VERY noticeable on Space Harrier's tittle screen music. 
-It's NOT related to high-CPU usage, as this happens on X86 and ARM, with a very low CPU usage.
-Tried different drivers for output and resampling and problem persists.
-Tried increasing buffer size and problem persists.
-Tried disabling audio sync and problem persists.

My guess is that these games don't refresh screen each ~16ms as most other PC Engine games do, so this causes audio problems because of how libretro/RA expects the emu to refresh screen and generate audio.

**Comment by Tatsuya79** [comment]
No problem here on win7 x64.
Standard audio config at 64ms, sync ON. Dsound driver.

**Comment by vanfanel** [comment]
@Tatsuya79 : Please compare the **music** on the tittle screen of Space Harrier with how it sounds on real hw or standalone Mednafen. Pay close attention when you do so.

It's not a matter of OS, audio driver or buffersize. It happens on Windows too, on RA/LR using the pce core.

**Comment by Oggom** [comment]
@vanfanel Try disabling VSync. There's a chance your display doesn't have a high enough refresh rate to keep up with the games which leads to audio crackling.

**Comment by vanfanel** [comment]
@Oggom I have several displays around for different platforms where RA/LR runs. It's the core: these two games (Space Harrier and Out Run) are the ONLY games that exhibit audio problems. Can you please listen to the Space Harrier tittle screen music carefully and compare it to standalone Mednafen? You **will** notice the problem.

**Comment by Tatsuya79** [comment]
I've got studio monitors on my PC and I can hear this popping on the high pitched notes in mednafen stand-alone too. 
That's less discernible than on retroarch though.
I wonder if that's perhaps just some sort of interpolation stand-alone does, or retroarch audio timing delta thing.

**Comment by c0d3h4x0r** [comment]
I hear audio crackling in "Sherlock Holmes: Consulting Detective" CD-ROM (during tail-end of the loading screen music, and much worse during the instruction audio for using your notebook icon), exclusively in this RetroArch core.  This happens on both my RetroPie (Pi3B+) and using RetroArch on my Win10 PC.  But when I load the same CD-ROM image using Magic Engine 1.1.3 on my Win10 PC, the crackling does not occur.  I've already ruled out system audio mixer levels, core-specific sound levels, and my audio playback hardware as signal clipping points, so this is purely due to a bug in the core.  Playing around with the sample rate, audio buffer size, etc in the RetroArch audio settings appears to have zero impact on the repro.

**Comment by c0d3h4x0r** [comment]
Been looking through the audio code (Blip_Buffer.c), and I spotted what appears to be an off-by-one error in Blip_Buffer_count_samples(): the returned count should be (last_sample - first_sample + 1), not (last_sample - first_sample).  Not saying that's the definitive cause of this issue, but it's possible.  Just the fact that I spotted that in my first 30 seconds of skimming the file tells me there are probably simple math bugs lurking in that code.

**Comment by c0d3h4x0r** [comment]
Also, in Blip_Buffer.h, Blip_Buffer.length is only of type 'int', while the code assumes it can hold a 'blip_s64', so there could very well be an overflow error there as well.

**Comment by hitsfromdabong** [comment]
I can confirm this is also the case with the game Crash Bandicoot. Game is laggy and audio very noisy (said crackling). No problem though when audio is disabled. Also changing the `sound.driver` to a different driver does not help at all.

I'm running macOS.

Version:
```
Mednafen 1.21.3
 Build information:
   Compiled with gcc 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.43.1)
   Compiled against zlib 1.2.11, running with zlib 1.2.11(flags=0x000000a9)
   Compiled against libiconv 11.1, running with libiconv 11.1
   Compiled against SDL 2.0.8(hg-11914:f1084c419f33), running with SDL 2.0.9(hg-12373:8feb5da6f2fb)
   Running with libsndfile-1.0.28
```

PS: Although I just realized that this is only a fork of the original mednafen, I just finished this text and it might be helpful in case the bug is also present in the original mednafen, so I'll just post ;)

**Comment by c0d3h4x0r** [comment]
Crash Bandicoot isn’t even a PCEngine/TurboGrafx16 game.

**Comment by sergioad** [comment]
How can ai apply the changes? Im using Recalbox be and I am getting choppy audio in Space harrier too

**Comment by Paladoc** [comment]
> @vanfanel Try disabling VSync. There's a chance your display doesn't have a high enough refresh rate to keep up with the games which leads to audio crackling.

Just wanted to say @oggom, disabling Vsync helped me on a Turbo Grafx CD issue.  I would never have thought to look at the Video options as causing some very annoying crackles.  Cheers mate, thanks so much to 7 years past you for that post :)
