### ISSUE TITLE
Problems with Turbo

### ISSUE THREAD

**Issue by striche2** [libretro/beetle-pce-fast-libretro#58]
It appears sometime in Jan a turbo feature was added (https://github.com/libretro/beetle-pce-fast-libretro/commit/afffa41b65cb4c82eb29831f872377ee8ba59ede).  However the feature seems to assume that you would never remap your button I and button II. In my case, I have remapped my buttons such that what I now use as button II is the same as toggling turbo for button II. This leads to...obvious problems.  I can see no way to remap the turbo buttons. I also can't seem to turn the feature off. The code "appears" to need a setting called "Turbo_Toggling" assigned to "enabled" to turn on, but I can't find any reference to a Turbo_Toggling setting in my files, suggesting there may be an error in checking whether the feature should be enabled/disabled.

**Comment by hizzlekizzle** [comment]
Yeah, looks like there should be a core option entry that never got added (should go [down here somewhere](https://github.com/libretro/beetle-pce-fast-libretro/blob/master/libretro.cpp#L1816)). I'll try to get that added in sometime soon, unless you want to send a PR before I get to it :)

**Comment by prataczak** [comment]
I just came to bring up the same thing. :)

The ideal mapping for turbo toggles to me is L3 and R3. They're out of the way, easily accessible, and won't interfere with anything else.

But I just wanted to add, whoever decided to implement this, you're awesome! In fact, I owe someone $25. :) I offered a reward for this feature a few months back when I came up with the idea of adding turbo buttons to the NEStopia core. So, whoever implemented this, PM me with your email, and I'll send you a paypal payment.

**Comment by prataczak** [comment]
I don't see a bounty link anywhere. Can I make this a bounty?

**Comment by twinaphex** [comment]
Go to bountysource, register an account, copy and paste the URL of this issue, paste it into the address bar on bountysource, click on 'Post'.

Then add money to the bounty.

**Comment by prataczak** [comment]
Cool, thanks.

**Comment by prataczak** [comment]
@hizzlekizzle would you be so kind as to build your version with the fix for me? I have Windows 10/RetroArch 1.5.0.

I would really like to see this issue fixed - for me, it's the only thing keeping the emulation for this system from being completely perfect.

**Comment by hizzlekizzle** [comment]
@prataczak 
I assumed win64: http://www.mediafire.com/file/z8yuod2ops4xdld/mednafen_pce_fast_libretro.dll

Let me know if that gets you fixed up and I'll PR it to the main repo.

**Comment by prataczak** [comment]
Thanks for the upload - yes, win64.

Your fix addresses part of the problem. There is now a 'turbo toggling' setting, so people who were having issues with the pre-defined turbo toggle buttons can simply turn it off. So it is definitely improvement over the existing build for that reason.

But what I am truly hoping for here is the ability to re-map the pre-defined turbo buttons to any key. Sometimes people need their buttons to be configured a certain way to work with their gamepad and/or personal preferences, and the current implementation of the turbo toggles will only work for some people/gamepads.

**Comment by retro-wertz** [comment]
you can remap using Menu > controller and remap button III (for button II
on/off) and button IV (for button I on/off)

**Comment by prataczak** [comment]
Yes but it would be better if 'button I on/off' and 'button II' on off was not automatically hard mapped to buttons III and IV.

If you need buttons III an IV put in specific locations for 6 button mode, it might conflict with things (as the OP pointed out) if you are using 2 button mode. That's the whole issue here. They should be their own entities, and you should be able to put them wherever you want.

**Comment by retro-wertz** [comment]
ok noted. a core option for switching X/Y on/off to L3/R3 would probably do.

**Comment by prataczak** [comment]
I appreciate any help you have to offer regarding this situation, so please don't misunderstand me. :)

But again, it should be up to the user to decide where it's convenient. Some people might not even be using gamepads with L3 and R3 buttons.

The turbo toggles should appear in the quick menu as their own separate entries, and you should be able to decide what button to map them to. That is the ideal solution for everyone, because the user gets to decide where it's convenient to put them.

**Comment by retro-wertz** [comment]
ok, got something similar to what you wanted, but its on supergrafx, the code should be the same though, although i am not entirely sure if this the the "right" way of doing it(on a programming layout perspective).

https://pastebin.com/c2xkYKnE

@hizzlekizzle should be able to create a new core from that, but i think he is busy so just wait up.

**Comment by prataczak** [comment]
Thanks retro-wertz. :)

**Comment by prataczak** [comment]
@retro-wertz if your fix works I would like you to claim the bounty I posted so that it does not go to waste.

I appreciate your help regardless but the whole point of the bounty system is to reward people who solve problems, and if you've solved my problem, then you've definitely earned it. :)

**Comment by retro-wertz** [comment]
i never pushed remap for turbo on/off to L3/R3 as you can just use Save Game Remap File/Save Core Remap File for those. For games that user 4/6 buttons, i remap as needed and use Save Game Remap so that when i reload these games again, remaps are automatically set... Then use Save Core Remap for all the 2-button games as there are a whole lot more 2-button games anyways.

**Comment by prataczak** [comment]
You can't remap them currently, that's the issue here.

**Comment by prataczak** [comment]
They're hard mapped to buttons III and IV, so whatever you have III and IV set to is where your turbo buttons will be.

**Comment by retro-wertz** [comment]
in pce? are you using the individual button turbo on/off in core? or do you mean the X/Y hotkey to turn turbo on button II and I?

**Comment by prataczak** [comment]
Yes, someone implemented hotkeys, and they hard mapped them to III and IV instead of making them their own separate entries that  you can map anywhere.

**Comment by retro-wertz** [comment]
i dont see a remap issue here, although i see another issue which is if you already enabled turbo using X/Y hotkey in 2-button mode, switching to 6-button does not turn off turbo for button I and II.

**Comment by prataczak** [comment]
The only way to remap the turbo hotkeys is to remap buttons III and IV. In other emulators, there would simply be a 'Turbo button I' and 'Turbo button II.'

I need III and IV where I need them. And I need turbo I and turbo II toggles elsewhere. :)

**Comment by retro-wertz** [comment]
thats where save core/save game remap file comes in, as you do not need button III and IV for 2-button games.

**Comment by prataczak** [comment]
I mean I *suppose* that is a solution, but ideally, you could set everything up one time, and not have to figure which games need remaps.

What is the point of having a toggle 2 button/6 button mode, if I still have to configure all the 6 button games?

I'm not trying to seem ungrateful here. I'm glad there are turbo toggles. But I offered a $25 bounty for the ability to move the turbo toggle keys independently from buttons III and IV, and that is what I'd like to see happen.

If you're not personally interested in fixing that, that's fine, I won't hold it against you. But it's still something I'd like to see implemented. :)

**Comment by prataczak** [comment]
I'm going to try one more time to present my case. I have a Hori EX Turbo controller that I use. Here is the current button mapping:

![example1](https://user-images.githubusercontent.com/12243933/33516919-9da73fcc-d748-11e7-9e50-f63872c234dc.png)

As you can see, I have the buttons mapped exactly the way they would be on a real 6 button controller. However, with the current implementation of the 'turbo toggle' buttons, they are not in an ideal location. What I want is this:

![example 2](https://user-images.githubusercontent.com/12243933/33516935-d95d2bc6-d748-11e7-8c7c-f408fb5b3291.png)

In this example, the 'turbo toggle' buttons are independent of buttons III and IV. With all due respect (because I know you guys work hard), it should have been implemented this way in the first place. The best solution is a solution that allows the end user to custom configure things in a way that works for their own personal setup. That is not the case here. Here, the user is forced to use the setup given to them.

Making remap files for every 6 player game is a huge hassle. I already have the controller set up exactly the way I want it.

@retro-wertz , you did such a nice job implementing the turbo toggle buttons in the PC-FX core. Can't you please implement it the same way here, and make the buttons independent of buttons III and IV? I. I am a huge TurboGrafx/NEC fan. The current implementation is very awkward for me.

**Comment by prataczak** [comment]
I upped the bounty from $25 to $70.

**Comment by prataczak** [comment]
To be clear also I want this feature added to both PCE Fast and the Supergrafx core.

**Comment by hizzlekizzle** [comment]
Implemented in #76
