### ISSUE TITLE
CHD - Uncorrectable data

### ISSUE THREAD

**Issue by dvessel** [libretro/beetle-pce-fast-libretro#91]
CHD files are unreadable. When pressing run to load the CD a notification stating "Uncorrectable data at sector xxxx" where xxxx is the start of the data track.

Decompressing the CHD file will allow it to play and the beetle-supergrafx-libretro core plays the CHD without problems.

**Comment by twinaphex** [comment]
Can you tell me if this started happening recently?

Can you poinpoint to a version where it was still working if so? Note - I need an exact Git revision, being told 'it worked on that day or whatever or within that month' will not be helpful.

I ask because the libchdr code has recently been updated in these cores, and to avoid a scenario where the libchdr code is wildly out of lockstep with the rest of RetroArch, we need to make sure that this time people can stay on the same page.

**Comment by dvessel** [comment]
It stopped working after updating the core this morning. I dug into my backups and the most recent version I have that works is from 2 days ago, April 21st.

Sorry, I'm not sure of the exact git version and I don't know how to compile from source.

**Comment by twinaphex** [comment]
That sucks, and was exactly what I did not want to hear.

**Comment by dvessel** [comment]
I was getting crashes with Mednafen Saturn core too but it looks like all the CHD changes were reverted and all is well right now. Closing and Thank you for all the amazing work.
